- name: Variables
  hosts: localhost
  vars:
   Courses: "Ansible"
   Trainer: "sivakumar"
   Duration: "120hrs"
  tasks:
  - name: print override information
    vars:
      courses: "Devops"
    ansible.builtin.debug:
     msg: "Hi, we are learning {{Courses}} from Trainer {{Trainer}}, Duration is {{Duration}}."
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Courses}} from Trainer {{Trainer}}, Duration is {{Duration}}."